version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: anderson123!
      MYSQL_DATABASE: coderhouse
      MYSQL_USER: anderson
      MYSQL_PASSWORD: anderson123!
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_scripts/:/home/scripts
    ports:
      - "3306:3306"
