apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: docker.io/library/mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: anderson123!
      - name: MYSQL_DATABASE
        value: coderhouse
      - name: MYSQL_USER
        value: anderson
      - name: MYSQL_PASSWORD
        value: anderson123!
    ports:
      - containerPort: 3306
        hostPort: 3306
    volumeMounts:
      - name: storage
        mountPath: /var/lib/mysql
      - name: scripts
        mountPath: /home/scripts

  volumes:
    - name: storage
      hostPath:
        path: /home/ander/Desktop/mysql_database/mysql_data
    - name: scripts
      hostPath:
        path: /home/ander/Desktop/mysql_database/scripts
        